['git', 'clone', '-q', '--single-branch', '-b', 'main', 'https://github.com/Skyehackerdoge/tds_project2.git', '/root/.local/share/tds-sep-24-project-2/21f3002090']





------------------------------------------------------------------------

['uv', 'run', '/root/.local/share/tds-sep-24-project-2/21f3002090/autolysis.py', '/root/.local/share/tds-sep-24-project-2/datasets/goodreads.csv']

Installing missing library: scikit-learn


Reading inline script metadata from `/root/.local/share/tds-sep-24-project-2/21f3002090/autolysis.py`
/root/.cache/uv/archive-v0/ouqwxxmm2amGQt6sbc6XV/bin/python3: No module named pip
Traceback (most recent call last):
  File "/root/.local/share/tds-sep-24-project-2/21f3002090/autolysis.py", line 33, in <module>
    __import__(lib)
    ~~~~~~~~~~^^^^^
ModuleNotFoundError: No module named 'scikit-learn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/tds-sep-24-project-2/21f3002090/autolysis.py", line 36, in <module>
    subprocess.check_call([sys.executable, "-m", "pip", "install", lib])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.13.1-linux-x86_64-gnu/lib/python3.13/subprocess.py", line 419, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/.cache/uv/archive-v0/ouqwxxmm2amGQt6sbc6XV/bin/python3', '-m', 'pip', 'install', 'scikit-learn']' returned non-zero exit status 1.


------------------------------------------------------------------------

